# Create this file as 'train_xgboost.py' in the same folder as your other train script.

import pickle
import pandas as pd
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

# --- 1. Load Merged Feature Matrices ---
print("Step 1: Loading data from '/models/merged/'...")
with open("../../models/merged/X_train.pkl", "rb") as f:
    X_train = pickle.load(f)

with open("../../models/merged/y_train.pkl", "rb") as f:
    y_train = pickle.load(f) # y_train is still text labels

# THIS IS THE FIX: We need to load X_test for the quick check
with open("../../models/merged/X_test.pkl", "rb") as f:
    X_test = pickle.load(f) 

with open("../../models/merged/y_test.pkl", "rb") as f:
    y_test = pickle.load(f) # y_test is still text labels
print("Data loading complete.")

# --- 2. Encode Text Labels to Integers ---
# XGBoost requires integer labels (0, 1, 2...) instead of strings.
print("Step 2: Encoding text labels to integers...")
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test) # Use the same encoder for test set

# Save the encoder so we can decode the predictions later
output_encoder_path = "../../models/merged/label_encoder.pkl"
with open(output_encoder_path, "wb") as f:
    pickle.dump(encoder, f)
print(f"Label encoder saved to {output_encoder_path}")


# --- 3. Initialize XGBoost Classifier ---
print("Step 3: Initializing XGBClassifier model...")
# Using 'multi:softmax' for multi-class classification
# 'n_jobs=-1' uses all available CPU cores to speed up training
xgb_clf = XGBClassifier(
    objective='multi:softmax', 
    num_class=len(encoder.classes_), 
    n_jobs=-1, 
    random_state=42
)

# --- 4. Train the Model ---
print("Step 4: Training the XGBoost classifier...")
xgb_clf.fit(X_train, y_train_encoded)
print("Training complete.")

# --- 5. Save the Trained Model ---
print("Step 5: Saving the trained XGBoost model...")
output_path = "../../models/merged/xgboost_model.pkl"
with open(output_path, "wb") as f:
    pickle.dump(xgb_clf, f)
print(f"Trained XGBoost model saved to {output_path}")

# --- 6. Quick Evaluation Check ---
print("\n--- Quick Performance Check (XGBoost) ---")
y_pred_encoded = xgb_clf.predict(X_test) # This line will now work
print("Accuracy:", accuracy_score(y_test_encoded, y_pred_encoded))
print("\n(Note: A full report will be generated by evaluate_xgboost.py)")